/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.hlo.world;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    
}
